version: '3.8'

services:
  # Service 1: The Backend API
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=""
      - GEMINI_API_KEY=""
      - JWT_SECRET=mysecret

  # Service 2: The Frontend Website
  client:
    build: ./client
    ports:
      - "80:80"  # Opens your app on localhost:80
    depends_on:
      - server